name: redstone_mapper
version: 0.2.0
authors:
- Luiz Mineo <luiz.mineo@gmail.com>
- Joel Trottier-Hebert <iamquebecois@gmail.com>
description: A mapper plugin for Redstone.dart
homepage: http://redstonedart.org
environment:
  sdk: '>=1.9.0-dev.9.1 <2.0.0'
dependencies:
  redstone:
  analyzer: "^0.27.0"
  code_transformers: ">= 0.3.1 <= 0.4.0"
  di: "^3.3.6"
dev_dependencies:
  test: "^0.12.6"
transformers:
  - redstone_mapper
  - test/pub_serve:
      $include: test/client_test.dart
